#!/usr/bin/env bash
URL="$1"
HOST="$2"
DB="$3"
USER="$4"
PASSWORD="$5"

spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

if [[ -e config/config.php ]]; then
    echo "File config/config.php already exists "
    echo "Generating confing file..."
    spinner &
    spinner_id=$!
    #Clear
    echo "<?php" > config/config.php
    echo "#File generated by deployment.sh" >> config/config.php
    echo "  define('URL', '"$URL"');" >> config/config.php
    echo "  define('HOST', '"$HOST"');" >> config/config.php
    echo "  define('DB', '"$DB"');" >> config/config.php
    echo "  define('USER', '"$USER"' );" >> config/config.php
    echo "  define('PASSWORD', '"$PASSWORD"');" >> config/config.php
    echo "  define('CHARSET', 'utf8mb4');" >> config/config.php
    echo "?>" >> config/config.php
    echo "config file generated" 
    kill $spinner_id &>/dev/null
else
    echo "Error: config/config.php does not exists"
fi 
