on: 
  pull_request:
    types: [closed]
        
  repository_dispatch:

name: ftp-deplyment
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SITE }}
        sername: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
