on: 
  pull_request:
    types: [closed]
        
  workflow_dispatch:

name: ftp-deplyment
jobs:
  web-deploy:
    name:  Deploy
    environment: x10hosting
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Make deploy script executable
      run: chmod +x deploy.sh
    - name: Create environment variables
      run: |
        ./deploy.sh ${{ secrets.SITE_URL }} \
                    ${{ secrets.SITE_HOST }} \
                    ${{ secrets.DATABASE_NAME }} \
                    ${{ secrets.DATABASE_USER }} \
                    ${{ secrets.DATABASE_PASSWORD }}
          
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SITE }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        exclude: |
          **/.vscode/*
          **/README.md
          **/TODO.drawio
          **/.git*
          **/.git*/**
          **/node_modules/**
          deploy.sh
